version: "3.8"
services:
  devcontainer:
    build: .
    volumes:
      - ../.:/workspace:cached
    command: sleep infinity
    environment:
      - CONNECTION_STRING=postgresql+psycopg2://postgres:password@db:5432/postgres
  db:
    container_name: db
    image: postgres:16.1
    restart: unless-stopped
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
volumes:
  postgres-data:
